

# This file was *autogenerated* from the file hola.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f = Integer(0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f); _sage_const_0x0000000000000000000000000000000000000000000000000000000000000000 = Integer(0x0000000000000000000000000000000000000000000000000000000000000000); _sage_const_0x0000000000000000000000000000000000000000000000000000000000000007 = Integer(0x0000000000000000000000000000000000000000000000000000000000000007); _sage_const_0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 = Integer(0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798); _sage_const_0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8 = Integer(0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8); _sage_const_0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141 = Integer(0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141); _sage_const_0x1 = Integer(0x1); _sage_const_8671863972918644020891893592264002636093783139480427895849310236719348461381201964156671118636441836060545823975787713255918690787156950587491048317621367 = Integer(8671863972918644020891893592264002636093783139480427895849310236719348461381201964156671118636441836060545823975787713255918690787156950587491048317621367); _sage_const_7107248759369583645199803455182591408419807886664892570248268912988152997296738707525728292531494273967624165497625607692935228944726023953531942664870243 = Integer(7107248759369583645199803455182591408419807886664892570248268912988152997296738707525728292531494273967624165497625607692935228944726023953531942664870243); _sage_const_262352607692351500239567664846202472581 = Integer(262352607692351500239567664846202472581); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_123 = Integer(123); _sage_const_1234 = Integer(1234)
p = _sage_const_0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f 
K = GF(p)
a = K(_sage_const_0x0000000000000000000000000000000000000000000000000000000000000000 )
b = K(_sage_const_0x0000000000000000000000000000000000000000000000000000000000000007 )
E = EllipticCurve(K, (a, b))
G = E(_sage_const_0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 , _sage_const_0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8 )
E.set_order(_sage_const_0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141  * _sage_const_0x1 )

key = _sage_const_8671863972918644020891893592264002636093783139480427895849310236719348461381201964156671118636441836060545823975787713255918690787156950587491048317621367 
publik = G*key

k1 = _sage_const_7107248759369583645199803455182591408419807886664892570248268912988152997296738707525728292531494273967624165497625607692935228944726023953531942664870243 

difft = _sage_const_262352607692351500239567664846202472581 
k2 = k1 + difft

q = E.order()

def recv(sign1, sign2, h1, h2, diff):
    r1, s1 = sign1
    r2, s2 = sign2
    k1 = ((int(r1) * h2 - int(r1) * int(s2) * diff - int(r2) * h1) * pow((int(r1) * int(s2) - int(s1) * r2), -_sage_const_1 , q)) %q
    return k1

def sign(m, k, sk, pk):
    r = k*G
    rx = int(r.xy()[_sage_const_0 ])
    s = (int(pow(k, -_sage_const_1 , q)) * (m + (rx * sk) % q ) % q ) % q
    return rx, s

def verify(m, r, s, pk):
    print(GCD(s, q))
    s1 = int(pow(s, -_sage_const_1 , q))
    R_ = ((m * s1) * G) + (r * s1) * pk
    print(R_.xy()[_sage_const_0 ])
    return int(r) == int(R_.xy()[_sage_const_0 ])

sg1 = sign(_sage_const_123 , k1, key, publik)
sg2 = sign(_sage_const_1234 , k2, key, publik)
#print(sg1) 
ver1 = verify(_sage_const_123 , sg1[_sage_const_0 ], sg1[_sage_const_1 ], publik)
ver2 = verify(_sage_const_1234 , sg2[_sage_const_0 ], sg2[_sage_const_1 ], publik)
#print(ver1)
#print(ver2)
recov = recv(sg1, sg2, _sage_const_123 , _sage_const_1234 , difft)
#print(recov)
#print(k1%q)

m1 = _sage_const_123 
m2 = _sage_const_1234 
r1 = sg1[_sage_const_0 ]
r2 = sg2[_sage_const_0 ]
s1 = sg1[_sage_const_1 ]
s2 = sg2[_sage_const_1 ]
# dec
df = (m2 * r1 - m1 * r2) % q
koef1 = (s2 * r1) % q
koef2 = (s1 * r2) % q
print("Delegations!!")
print(df)
print(koef1)
print(koef2)
print("\n")
print("Rules")
inv_koef1 = int(pow(koef1, -_sage_const_1 , q))
base_1 = (df * inv_koef1) % q
base_2 = (koef2 * inv_koef1) % q
print(base_1)
print(base_2)

print((base_2 * k1 + base_1)%q)
print(k2%q)
print("founded cores!!")
intv = (s1 * r2 - base_2 * s2 * r1)
print(intv)
print(gcd(intv, q))
kk = ((m1 * r2 + s2 * base_1 * r1 - m2 * r1) % q * int(pow(intv, -_sage_const_1 , q))) % q
print(kk)
print(k1%q)

